// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class AlertBannerComponentHandle extends ffai.ProjectComponentHandle<AlertBannerParams, AlertBannerState> {
  AlertBannerComponentHandle()
    : super(
        name: "AlertBanner",
        key: "Container_v5j06s4j",
        params: const AlertBannerParams(),
        state: const AlertBannerState(),
        widgets: AlertBannerWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "message": ffai.string,
          "title": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? message = ffai.kUnsetComponentArg,
    Object? title = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(message)) "message": message,
        if (!ffai.isUnsetComponentArg(title)) "title": title,
      },
    );
  }
}

final class AlertBannerParams {
  const AlertBannerParams();
  ffai.ProjectParamHandle get message =>
      const ffai.ProjectParamHandle(
        name: "message",
        key: "0t82vsxb",
        typeName: "String",
      );
  ffai.ProjectParamHandle get title =>
      const ffai.ProjectParamHandle(
        name: "title",
        key: "3ip71z30",
        typeName: "String",
      );
}

final class AlertBannerState {
  const AlertBannerState();
}

abstract final class AlertBannerWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_v5j06s4j",
      type: "Container",
      path: "AlertBanner",
      name: "AlertBanner",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_gfx8sqvk",
          type: "Container",
          path: "AlertBanner.children[0]",
          name: "Container",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Row_tlerz8k0",
              type: "Row",
              path: "AlertBanner.children[0].children[0]",
              name: "Row",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Icon_q6r48t1s",
                  type: "Icon",
                  path: "AlertBanner.children[0].children[0].children[0]",
                  name: "Icon",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Column_2esjodmf",
                  type: "Column",
                  path: "AlertBanner.children[0].children[0].children[1]",
                  name: "Column",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Text_v4il1kz9",
                      type: "Text",
                      path: "AlertBanner.children[0].children[0].children[1].children[0]",
                      name: "Text",
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Text_mlk0obvk",
                      type: "Text",
                      path: "AlertBanner.children[0].children[0].children[1].children[1]",
                      name: "Text",
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

