// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class CaseFooterComponentHandle extends ffai.ProjectComponentHandle<CaseFooterParams, CaseFooterState> {
  CaseFooterComponentHandle()
    : super(
        name: "CaseFooter",
        key: "Container_vs7x0u8n",
        params: const CaseFooterParams(),
        state: const CaseFooterState(),
        widgets: CaseFooterWidgets.tree,
        paramTypes: <String, ffai.DslType>{
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
      },
    );
  }
}

final class CaseFooterParams {
  const CaseFooterParams();
}

final class CaseFooterState {
  const CaseFooterState();
}

abstract final class CaseFooterWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_vs7x0u8n",
      type: "Container",
      path: "CaseFooter",
      name: "CaseFooter",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Text_005ztq52",
          type: "Text",
          path: "CaseFooter.children[0]",
          name: "Text",
          text: "FORM KYA-001B  •  CASE ID: KYA-0018  •  RISK: SLEEPY",
        ),
      ],
    ),
  );
}

