// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class ChatBubbleComponentHandle extends ffai.ProjectComponentHandle<ChatBubbleParams, ChatBubbleState> {
  ChatBubbleComponentHandle()
    : super(
        name: "ChatBubble",
        key: "Container_decyh8xy",
        params: const ChatBubbleParams(),
        state: const ChatBubbleState(),
        widgets: ChatBubbleWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "fromOfficer": ffai.bool_,
          "rejected": ffai.bool_,
          "text": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? fromOfficer = ffai.kUnsetComponentArg,
    Object? rejected = ffai.kUnsetComponentArg,
    Object? text = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(fromOfficer)) "fromOfficer": fromOfficer,
        if (!ffai.isUnsetComponentArg(rejected)) "rejected": rejected,
        if (!ffai.isUnsetComponentArg(text)) "text": text,
      },
    );
  }
}

final class ChatBubbleParams {
  const ChatBubbleParams();
  ffai.ProjectParamHandle get fromOfficer =>
      const ffai.ProjectParamHandle(
        name: "fromOfficer",
        key: "ren7v3re",
        typeName: "Boolean",
      );
  ffai.ProjectParamHandle get rejected =>
      const ffai.ProjectParamHandle(
        name: "rejected",
        key: "os4wz904",
        typeName: "Boolean",
      );
  ffai.ProjectParamHandle get text =>
      const ffai.ProjectParamHandle(
        name: "text",
        key: "jvpn07md",
        typeName: "String",
      );
}

final class ChatBubbleState {
  const ChatBubbleState();
}

abstract final class ChatBubbleWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_decyh8xy",
      type: "Container",
      path: "ChatBubble",
      name: "ChatBubble",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Column_bugvn8zy",
          type: "Column",
          path: "ChatBubble.children[0]",
          name: "Column",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Row_8yggiuew",
              type: "Row",
              path: "ChatBubble.children[0].children[0]",
              name: "Row",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_trabu1ts",
                  type: "Container",
                  path: "ChatBubble.children[0].children[0].children[0]",
                  name: "Container",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Text_o1ialp4k",
                      type: "Text",
                      path: "ChatBubble.children[0].children[0].children[0].children[0]",
                      name: "Text",
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_lgxcrcc0",
                  type: "Container",
                  path: "ChatBubble.children[0].children[0].children[1]",
                  name: "Container",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Text_xk18gymh",
                      type: "Text",
                      path: "ChatBubble.children[0].children[0].children[1].children[0]",
                      name: "Text",
                    ),
                  ],
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Row_2v3aljbv",
              type: "Row",
              path: "ChatBubble.children[0].children[1]",
              name: "Row",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_8k4d9muh",
                  type: "Container",
                  path: "ChatBubble.children[0].children[1].children[0]",
                  name: "Container",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Text_qjt12698",
                      type: "Text",
                      path: "ChatBubble.children[0].children[1].children[0].children[0]",
                      name: "Text",
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

