// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class OfficialSealComponentHandle extends ffai.ProjectComponentHandle<OfficialSealParams, OfficialSealState> {
  OfficialSealComponentHandle()
    : super(
        name: "OfficialSeal",
        key: "Container_v89l2giu",
        params: const OfficialSealParams(),
        state: const OfficialSealState(),
        widgets: OfficialSealWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "square": ffai.bool_,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? square = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(square)) "square": square,
      },
    );
  }
}

final class OfficialSealParams {
  const OfficialSealParams();
  ffai.ProjectParamHandle get square =>
      const ffai.ProjectParamHandle(
        name: "square",
        key: "wihyjisg",
        typeName: "Boolean",
      );
}

final class OfficialSealState {
  const OfficialSealState();
}

abstract final class OfficialSealWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_v89l2giu",
      type: "Container",
      path: "OfficialSeal",
      name: "OfficialSeal",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Stack_w3whgq0t",
          type: "Stack",
          path: "OfficialSeal.children[0]",
          name: "Stack",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Container_ls6hkm9r",
              type: "Container",
              path: "OfficialSeal.children[0].children[0]",
              name: "Container",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Icon_a5lqfk9v",
                  type: "Icon",
                  path: "OfficialSeal.children[0].children[0].children[0]",
                  name: "Icon",
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Container_ecagv0rm",
              type: "Container",
              path: "OfficialSeal.children[0].children[1]",
              name: "Container",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Icon_gtm9pos3",
                  type: "Icon",
                  path: "OfficialSeal.children[0].children[1].children[0]",
                  name: "Icon",
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

