// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class StepProgressComponentHandle extends ffai.ProjectComponentHandle<StepProgressParams, StepProgressState> {
  StepProgressComponentHandle()
    : super(
        name: "StepProgress",
        key: "Container_y9fwi3jk",
        params: const StepProgressParams(),
        state: const StepProgressState(),
        widgets: StepProgressWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "label": ffai.string,
          "step": ffai.int_,
          "value": ffai.double_,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? label = ffai.kUnsetComponentArg,
    Object? step = ffai.kUnsetComponentArg,
    Object? value = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(label)) "label": label,
        if (!ffai.isUnsetComponentArg(step)) "step": step,
        if (!ffai.isUnsetComponentArg(value)) "value": value,
      },
    );
  }
}

final class StepProgressParams {
  const StepProgressParams();
  ffai.ProjectParamHandle get label =>
      const ffai.ProjectParamHandle(
        name: "label",
        key: "12capgl3",
        typeName: "String",
      );
  ffai.ProjectParamHandle get step =>
      const ffai.ProjectParamHandle(
        name: "step",
        key: "x2vve8rm",
        typeName: "Integer",
      );
  ffai.ProjectParamHandle get value =>
      const ffai.ProjectParamHandle(
        name: "value",
        key: "52c2q8ez",
        typeName: "Double",
      );
}

final class StepProgressState {
  const StepProgressState();
}

abstract final class StepProgressWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_y9fwi3jk",
      type: "Container",
      path: "StepProgress",
      name: "StepProgress",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Column_orklpb79",
          type: "Column",
          path: "StepProgress.children[0]",
          name: "Column",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Row_e1bdzp0w",
              type: "Row",
              path: "StepProgress.children[0].children[0]",
              name: "Row",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_jnk75ctj",
                  type: "Text",
                  path: "StepProgress.children[0].children[0].children[0]",
                  name: "Text",
                  text: "STEP ",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Text_6l87f5fx",
                  type: "Text",
                  path: "StepProgress.children[0].children[0].children[1]",
                  name: "Text",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Text_x7v97vts",
                  type: "Text",
                  path: "StepProgress.children[0].children[0].children[2]",
                  name: "Text",
                  text: " OF 4",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Text_nwyft9k1",
                  type: "Text",
                  path: "StepProgress.children[0].children[0].children[3]",
                  name: "Text",
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Container_fl51hk57",
              type: "Container",
              path: "StepProgress.children[0].children[1]",
              name: "StepProgressBar",
            ),
          ],
        ),
      ],
    ),
  );
}

