// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final activeAlarmHandle = ffai.ProjectPageHandle<ActiveAlarmParams, ActiveAlarmState>(
  name: "ActiveAlarm",
  key: "Scaffold_6dcgnzt3",
  route: "",
  params: const ActiveAlarmParams(),
  state: const ActiveAlarmState(),
  widgets: ActiveAlarmWidgets.tree,
);

final class ActiveAlarmParams {
  const ActiveAlarmParams();
}

final class ActiveAlarmState {
  const ActiveAlarmState();
}

abstract final class ActiveAlarmWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_6dcgnzt3",
      type: "Scaffold",
      path: "ActiveAlarm",
      name: "ActiveAlarm",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_ewhe1lqg",
            type: "Container",
            path: "ActiveAlarm.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_0k1lvknv",
                type: "Column",
                path: "ActiveAlarm.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_9efa8s8s",
                    type: "Container",
                    path: "ActiveAlarm.body[0].children[0].children[0]",
                    name: "AlarmStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_18u9nwj8",
                        type: "Row",
                        path: "ActiveAlarm.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_uq22yv22",
                            type: "Text",
                            path: "ActiveAlarm.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_3l6zm21u",
                            type: "Text",
                            path: "ActiveAlarm.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_1ezs94r7",
                            type: "IconButton",
                            path: "ActiveAlarm.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_b3uk612c",
                    type: "Column",
                    path: "ActiveAlarm.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_5p4ee7ne",
                        type: "Container",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[0]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Image_j7ixifhk",
                        type: "Image",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[1]",
                        name: "AlbyHappy",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Image_byubqbmf",
                        type: "Image",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[2]",
                        name: "AlbySuspicious",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_cav7bvdk",
                        type: "Text",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[3]",
                        name: "Text",
                        text: "Good morning!",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_njfytoff",
                        type: "Text",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[4]",
                        name: "Text",
                        text: "Welcome back!",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_2zo5pgnv",
                        type: "Text",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[5]",
                        name: "Text",
                        text: "Rise and shine!\nA productive day awaits!",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_vwapyvi1",
                        type: "Text",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[6]",
                        name: "Text",
                        text: "Your authorized unconsciousness period has expired.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_yjanrh83",
                        type: "Text",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[7]",
                        name: "Text",
                        text: "6:00 AM",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_j8bdxuzw",
                        type: "Container",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[8]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_b5qz91w5",
                        type: "Button",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[9]",
                        name: "SnoozeButton",
                        text: "SNOOZE",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_4az1czfe",
                        type: "Text",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[10]",
                        name: "Text",
                        text: "30 minutes",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_x0zrtdgt",
                        type: "Button",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[11]",
                        name: "SnoozeAgainButton",
                        text: "REQUEST ANOTHER SNOOZE",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_293uvuqz",
                        type: "Button",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[12]",
                        name: "StopAlarmButton",
                        text: "Stop Alarm",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ptvnq6gv",
                        type: "Text",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[13]",
                        name: "Text",
                        text: "Discipline today. A better you tomorrow!",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_i0iccluj",
                        type: "Text",
                        path: "ActiveAlarm.body[0].children[0].children[1].children[14]",
                        name: "Text",
                        text: "Compliance is a lifestyle.",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

