// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final aisnoozeOfficerHandle = ffai.ProjectPageHandle<AisnoozeOfficerParams, AisnoozeOfficerState>(
  name: "AISnoozeOfficer",
  key: "Scaffold_rid02peo",
  route: "ai-snooze-officer",
  params: const AisnoozeOfficerParams(),
  state: const AisnoozeOfficerState(),
  widgets: AisnoozeOfficerWidgets.tree,
);

final class AisnoozeOfficerParams {
  const AisnoozeOfficerParams();
}

final class AisnoozeOfficerState {
  const AisnoozeOfficerState();
}

abstract final class AisnoozeOfficerWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_rid02peo",
      type: "Scaffold",
      path: "AISnoozeOfficer",
      name: "AISnoozeOfficer",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_e6ceietg",
            type: "Container",
            path: "AISnoozeOfficer.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_rw9e44q8",
                type: "Column",
                path: "AISnoozeOfficer.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_t7dcj61p",
                    type: "Container",
                    path: "AISnoozeOfficer.body[0].children[0].children[0]",
                    name: "OfficerStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_ohoaloxi",
                        type: "Row",
                        path: "AISnoozeOfficer.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_rz3twbvl",
                            type: "Text",
                            path: "AISnoozeOfficer.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_dem3ya6b",
                            type: "Text",
                            path: "AISnoozeOfficer.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_mtky9szu",
                            type: "IconButton",
                            path: "AISnoozeOfficer.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_i77tlpno",
                    type: "Column",
                    path: "AISnoozeOfficer.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_q1fk482p",
                        type: "Container",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[0]",
                        name: "OfficerStep",
                        componentName: "StepProgress",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Image_zuh2g1zg",
                        type: "Image",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[1]",
                        name: "AlbyOfficer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_n1jjvb1h",
                        type: "Text",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[2]",
                        name: "Text",
                        text: "AI Snooze Officer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ucarwz8y",
                        type: "Container",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[3]",
                        name: "OfficerGreeting",
                        componentName: "ChatBubble",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_40ux5xdi",
                        type: "Container",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[4]",
                        name: "OfficerUserReply",
                        componentName: "ChatBubble",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_k36vjlr7",
                        type: "Container",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[5]",
                        name: "OfficerRejection",
                        componentName: "ChatBubble",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_v99o6bcb",
                        type: "TextField",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[6]",
                        name: "officerField",
                        text: "Your testimony",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_jbresepj",
                        type: "Button",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[7]",
                        name: "SendTestimonyButton",
                        text: "SUBMIT TESTIMONY",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_33z716i5",
                        type: "Button",
                        path: "AISnoozeOfficer.body[0].children[0].children[1].children[8]",
                        name: "AppealButton",
                        text: "SUBMIT APPEAL ANYWAY",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

