// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final alarmStoppedHandle = ffai.ProjectPageHandle<AlarmStoppedParams, AlarmStoppedState>(
  name: "AlarmStopped",
  key: "Scaffold_3ark4uz6",
  route: "alarm-stopped",
  params: const AlarmStoppedParams(),
  state: const AlarmStoppedState(),
  widgets: AlarmStoppedWidgets.tree,
);

final class AlarmStoppedParams {
  const AlarmStoppedParams();
}

final class AlarmStoppedState {
  const AlarmStoppedState();
}

abstract final class AlarmStoppedWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_3ark4uz6",
      type: "Scaffold",
      path: "AlarmStopped",
      name: "AlarmStopped",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_23j634gx",
            type: "Container",
            path: "AlarmStopped.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_2d166a5o",
                type: "Column",
                path: "AlarmStopped.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_njjfwf2r",
                    type: "Column",
                    path: "AlarmStopped.body[0].children[0].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_mxwv319r",
                        type: "Container",
                        path: "AlarmStopped.body[0].children[0].children[0].children[0]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Icon_td0j9jtc",
                        type: "Icon",
                        path: "AlarmStopped.body[0].children[0].children[0].children[1]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_454ditsx",
                        type: "Text",
                        path: "AlarmStopped.body[0].children[0].children[0].children[2]",
                        name: "Text",
                        text: "Alarm stopped.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_5xxn2t62",
                        type: "Text",
                        path: "AlarmStopped.body[0].children[0].children[0].children[3]",
                        name: "Text",
                        text: "No forms. No appeals.\nSafety outranks the joke.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_44kjhabt",
                        type: "Container",
                        path: "AlarmStopped.body[0].children[0].children[0].children[4]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_ni653ghv",
                        type: "Button",
                        path: "AlarmStopped.body[0].children[0].children[0].children[5]",
                        name: "RestartDemoButton",
                        text: "RESTART DEMO",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

