// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final authorizedSnoozeHandle = ffai.ProjectPageHandle<AuthorizedSnoozeParams, AuthorizedSnoozeState>(
  name: "AuthorizedSnooze",
  key: "Scaffold_7eij0rq6",
  route: "authorized-snooze",
  params: const AuthorizedSnoozeParams(),
  state: const AuthorizedSnoozeState(),
  widgets: AuthorizedSnoozeWidgets.tree,
);

final class AuthorizedSnoozeParams {
  const AuthorizedSnoozeParams();
}

final class AuthorizedSnoozeState {
  const AuthorizedSnoozeState();
}

abstract final class AuthorizedSnoozeWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_7eij0rq6",
      type: "Scaffold",
      path: "AuthorizedSnooze",
      name: "AuthorizedSnooze",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_tcpbizt8",
            type: "Container",
            path: "AuthorizedSnooze.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_g1t00se3",
                type: "Column",
                path: "AuthorizedSnooze.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_k0m8n3ae",
                    type: "Container",
                    path: "AuthorizedSnooze.body[0].children[0].children[0]",
                    name: "SnoozingStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_y63v7q0m",
                        type: "Row",
                        path: "AuthorizedSnooze.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_wm2twhh4",
                            type: "Text",
                            path: "AuthorizedSnooze.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_id73608f",
                            type: "Text",
                            path: "AuthorizedSnooze.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_v8u04adz",
                            type: "IconButton",
                            path: "AuthorizedSnooze.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_wokk65nr",
                    type: "Column",
                    path: "AuthorizedSnooze.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_rkidhh6b",
                        type: "Container",
                        path: "AuthorizedSnooze.body[0].children[0].children[1].children[0]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Icon_xr75axu1",
                        type: "Icon",
                        path: "AuthorizedSnooze.body[0].children[0].children[1].children[1]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_wz0bxkzq",
                        type: "Text",
                        path: "AuthorizedSnooze.body[0].children[0].children[1].children[2]",
                        name: "Text",
                        text: "Authorized unconsciousness\nin progress",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_e4s8erib",
                        type: "Text",
                        path: "AuthorizedSnooze.body[0].children[0].children[1].children[3]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_uk9qkong",
                        type: "Text",
                        path: "AuthorizedSnooze.body[0].children[0].children[1].children[4]",
                        name: "Text",
                        text: "Please sleep efficiently.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_839fffuo",
                        type: "Container",
                        path: "AuthorizedSnooze.body[0].children[0].children[1].children[5]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_xu31i1vi",
                        type: "Button",
                        path: "AuthorizedSnooze.body[0].children[0].children[1].children[6]",
                        name: "WakeNowButton",
                        text: "WAKE ME NOW",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

