// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final bureaucraticProcessingHandle = ffai.ProjectPageHandle<BureaucraticProcessingParams, BureaucraticProcessingState>(
  name: "BureaucraticProcessing",
  key: "Scaffold_51vo9ewc",
  route: "bureaucratic-processing",
  params: const BureaucraticProcessingParams(),
  state: const BureaucraticProcessingState(),
  widgets: BureaucraticProcessingWidgets.tree,
);

final class BureaucraticProcessingParams {
  const BureaucraticProcessingParams();
}

final class BureaucraticProcessingState {
  const BureaucraticProcessingState();
}

abstract final class BureaucraticProcessingWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_51vo9ewc",
      type: "Scaffold",
      path: "BureaucraticProcessing",
      name: "BureaucraticProcessing",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_40ml6ml3",
            type: "Container",
            path: "BureaucraticProcessing.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_b88wbqm5",
                type: "Column",
                path: "BureaucraticProcessing.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_qgs4qzti",
                    type: "Container",
                    path: "BureaucraticProcessing.body[0].children[0].children[0]",
                    name: "ProcessingStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_ke7k88j7",
                        type: "Row",
                        path: "BureaucraticProcessing.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_o4nr11od",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_r33u202m",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_5p0ya8cp",
                            type: "IconButton",
                            path: "BureaucraticProcessing.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_0w1wthny",
                    type: "Column",
                    path: "BureaucraticProcessing.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_25jj2poc",
                        type: "Text",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[0]",
                        name: "Text",
                        text: "Processing your request...",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_q1i1z6qh",
                        type: "Container",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[1]",
                        name: "ProcessingSeal",
                        componentName: "OfficialSeal",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_ntt5kfc2",
                        type: "Row",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[2]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_hneducd9",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[2].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_kjii1xnk",
                            type: "ProgressBar",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[2].children[1]",
                            name: "ProgressBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_o40e0dtz",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[2].children[2]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_bntlc0kp",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[2].children[3]",
                            name: "Text",
                            text: "Reviewing your sleep history...",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_ajixe6ly",
                        type: "Row",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[3]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_uvbf40dn",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[3].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_xnjipaao",
                            type: "ProgressBar",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[3].children[1]",
                            name: "ProgressBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_r70pcffq",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[3].children[2]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_yxyay7lq",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[3].children[3]",
                            name: "Text",
                            text: "Contacting your pillow...",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_issntzwt",
                        type: "Row",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[4]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_zyrniglm",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[4].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_7m24rziq",
                            type: "ProgressBar",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[4].children[1]",
                            name: "ProgressBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_r4ttpnwb",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[4].children[2]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_j1sr36l0",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[4].children[3]",
                            name: "Text",
                            text: "Consulting the International Sleep Authority...",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_ginwrwin",
                        type: "Row",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[5]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_58jeg9tp",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[5].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_t7r3afvp",
                            type: "ProgressBar",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[5].children[1]",
                            name: "ProgressBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_zthusy4m",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[5].children[2]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_fvx96gwc",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[5].children[3]",
                            name: "Text",
                            text: "Evaluating vibes...",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_nsoa1zgd",
                        type: "Row",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[6]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_uj7qvcq0",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[6].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_adim9n15",
                            type: "ProgressBar",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[6].children[1]",
                            name: "ProgressBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_5lb3sdx1",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[6].children[2]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_mgj2w4nx",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[6].children[3]",
                            name: "Text",
                            text: "Determining whether you are actually tired...",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_kobt6z6n",
                        type: "Row",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[7]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_lvxrtskd",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[7].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_zu4mdryk",
                            type: "ProgressBar",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[7].children[1]",
                            name: "ProgressBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_4hpao7jf",
                            type: "Icon",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[7].children[2]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_xcm7arjw",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[7].children[3]",
                            name: "Text",
                            text: "Almost there...",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_v17r7tds",
                        type: "Row",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[8]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_mhla37m5",
                            type: "Container",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[8].children[0]",
                            name: "ProcessingBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_s0jyx42q",
                            type: "Text",
                            path: "BureaucraticProcessing.body[0].children[0].children[1].children[8].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_m5f7et5b",
                        type: "Text",
                        path: "BureaucraticProcessing.body[0].children[0].children[1].children[9]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

