// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final identityWakeCheckHandle = ffai.ProjectPageHandle<IdentityWakeCheckParams, IdentityWakeCheckState>(
  name: "IdentityWakeCheck",
  key: "Scaffold_6xordw2n",
  route: "identity-wake-check",
  params: const IdentityWakeCheckParams(),
  state: const IdentityWakeCheckState(),
  widgets: IdentityWakeCheckWidgets.tree,
);

final class IdentityWakeCheckParams {
  const IdentityWakeCheckParams();
}

final class IdentityWakeCheckState {
  const IdentityWakeCheckState();
}

abstract final class IdentityWakeCheckWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_6xordw2n",
      type: "Scaffold",
      path: "IdentityWakeCheck",
      name: "IdentityWakeCheck",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_urbiqc7k",
            type: "Container",
            path: "IdentityWakeCheck.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_lv69ijk8",
                type: "Column",
                path: "IdentityWakeCheck.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_zbka4bq3",
                    type: "Container",
                    path: "IdentityWakeCheck.body[0].children[0].children[0]",
                    name: "IdentityStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_9oic4q17",
                        type: "Row",
                        path: "IdentityWakeCheck.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_9529en5z",
                            type: "Text",
                            path: "IdentityWakeCheck.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_owzos7hu",
                            type: "Text",
                            path: "IdentityWakeCheck.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_hqrtrsjf",
                            type: "IconButton",
                            path: "IdentityWakeCheck.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_oq1oyy95",
                    type: "Column",
                    path: "IdentityWakeCheck.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_wtdbdelr",
                        type: "Container",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[0]",
                        name: "IdentityStep",
                        componentName: "StepProgress",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_6g5c0owi",
                        type: "Text",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[1]",
                        name: "Text",
                        text: "Identity Wake Check",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_wf0odkna",
                        type: "Text",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[2]",
                        name: "Text",
                        text: "One final scan before the alarm can be silenced.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_kjj1wz6h",
                        type: "Container",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[3]",
                        name: "IdentityFaceScan",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_prrhd8t1",
                        type: "Text",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[4]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_6ahuhsgq",
                        type: "Text",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[5]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_2yppy6l3",
                        type: "Container",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[6]",
                        name: "IdentityBar",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_k3w81gmn",
                        type: "Button",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[7]",
                        name: "StartIdentityScanButton",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_du6knvdq",
                        type: "Text",
                        path: "IdentityWakeCheck.body[0].children[0].children[1].children[8]",
                        name: "Text",
                        text: "Live preview only. Nothing is recorded, uploaded, or stored.",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

