// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final kyaintroductionHandle = ffai.ProjectPageHandle<KyaintroductionParams, KyaintroductionState>(
  name: "KYAIntroduction",
  key: "Scaffold_26uu75zu",
  route: "kya-introduction",
  params: const KyaintroductionParams(),
  state: const KyaintroductionState(),
  widgets: KyaintroductionWidgets.tree,
);

final class KyaintroductionParams {
  const KyaintroductionParams();
}

final class KyaintroductionState {
  const KyaintroductionState();
}

abstract final class KyaintroductionWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_26uu75zu",
      type: "Scaffold",
      path: "KYAIntroduction",
      name: "KYAIntroduction",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_268u5m5l",
            type: "Container",
            path: "KYAIntroduction.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_oq72b124",
                type: "Column",
                path: "KYAIntroduction.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_h1i7palf",
                    type: "Container",
                    path: "KYAIntroduction.body[0].children[0].children[0]",
                    name: "IntroStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_tqs7pu3m",
                        type: "Row",
                        path: "KYAIntroduction.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_6jqr2bgo",
                            type: "Text",
                            path: "KYAIntroduction.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_y0chim6h",
                            type: "Text",
                            path: "KYAIntroduction.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_fbiawstl",
                            type: "IconButton",
                            path: "KYAIntroduction.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_7wufkg1v",
                    type: "Column",
                    path: "KYAIntroduction.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_24qrb46l",
                        type: "Container",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[0]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_zrn7u53q",
                        type: "Text",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[1]",
                        name: "Text",
                        text: "KYA™",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_dqi77g6g",
                        type: "Text",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[2]",
                        name: "Text",
                        text: "Know Your Alarm",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_9vsinj2d",
                        type: "Container",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[3]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_x4yrjbh1",
                        type: "Container",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[4]",
                        name: "IntroSeal",
                        componentName: "OfficialSeal",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_t86rmrfx",
                        type: "Container",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[5]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ami9yoyr",
                        type: "Text",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[6]",
                        name: "Text",
                        text: "Snooze Termination\nRequest",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_n6mdztfc",
                        type: "Text",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[7]",
                        name: "Text",
                        text: "To comply with the International Sleep Prevention Act, all users must complete Know Your Alarm verification.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_rlvmcpnf",
                        type: "Container",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[8]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_sd82b94g",
                        type: "Button",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[9]",
                        name: "StartVerificationButton",
                        text: "START VERIFICATION",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_z7cb1r45",
                        type: "Container",
                        path: "KYAIntroduction.body[0].children[0].children[1].children[10]",
                        name: "IntroCaseFooter",
                        componentName: "CaseFooter",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

