// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final reasonForSnoozingHandle = ffai.ProjectPageHandle<ReasonForSnoozingParams, ReasonForSnoozingState>(
  name: "ReasonForSnoozing",
  key: "Scaffold_u1n8nese",
  route: "reason-for-snoozing",
  params: const ReasonForSnoozingParams(),
  state: const ReasonForSnoozingState(),
  widgets: ReasonForSnoozingWidgets.tree,
);

final class ReasonForSnoozingParams {
  const ReasonForSnoozingParams();
}

final class ReasonForSnoozingState {
  const ReasonForSnoozingState();
}

abstract final class ReasonForSnoozingWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_u1n8nese",
      type: "Scaffold",
      path: "ReasonForSnoozing",
      name: "ReasonForSnoozing",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_3a4njvd6",
            type: "Container",
            path: "ReasonForSnoozing.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_tos0v1xc",
                type: "Column",
                path: "ReasonForSnoozing.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_w0muqt85",
                    type: "Container",
                    path: "ReasonForSnoozing.body[0].children[0].children[0]",
                    name: "ReasonStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_5krwqf7x",
                        type: "Row",
                        path: "ReasonForSnoozing.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_jibdu420",
                            type: "Text",
                            path: "ReasonForSnoozing.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_9f2fm7u4",
                            type: "Text",
                            path: "ReasonForSnoozing.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_envrpsln",
                            type: "IconButton",
                            path: "ReasonForSnoozing.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_41ur21h2",
                    type: "Column",
                    path: "ReasonForSnoozing.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_khyxumk9",
                        type: "Container",
                        path: "ReasonForSnoozing.body[0].children[0].children[1].children[0]",
                        name: "ReasonStep",
                        componentName: "StepProgress",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_g13uco4o",
                        type: "Text",
                        path: "ReasonForSnoozing.body[0].children[0].children[1].children[1]",
                        name: "Text",
                        text: "Why are you snoozing?",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_dpt7qf6y",
                        type: "Container",
                        path: "ReasonForSnoozing.body[0].children[0].children[1].children[2]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "RadioButton_ye4xsg52",
                            type: "RadioButton",
                            path: "ReasonForSnoozing.body[0].children[0].children[1].children[2].children[0]",
                            name: "reasonRadio",
                            triggers: const <String>[
                              "ON_FORM_WIDGET_SELECTED",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_rcojisco",
                        type: "Text",
                        path: "ReasonForSnoozing.body[0].children[0].children[1].children[3]",
                        name: "Text",
                        text: "Explain why.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_rqj3ef4w",
                        type: "TextField",
                        path: "ReasonForSnoozing.body[0].children[0].children[1].children[4]",
                        name: "reasonField",
                        text: "Your statement",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_zxf5oczh",
                        type: "Text",
                        path: "ReasonForSnoozing.body[0].children[0].children[1].children[5]",
                        name: "Text",
                        text: "Minimum 50 characters of sleepy context.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_g3vpd17e",
                        type: "Text",
                        path: "ReasonForSnoozing.body[0].children[0].children[1].children[6]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_vohupqpy",
                        type: "Button",
                        path: "ReasonForSnoozing.body[0].children[0].children[1].children[7]",
                        name: "ReasonNextButton",
                        text: "NEXT",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

