// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final snoozeDodgeHandle = ffai.ProjectPageHandle<SnoozeDodgeParams, SnoozeDodgeState>(
  name: "SnoozeDodge",
  key: "Scaffold_snil9v3q",
  route: "snooze-dodge",
  params: const SnoozeDodgeParams(),
  state: const SnoozeDodgeState(),
  widgets: SnoozeDodgeWidgets.tree,
);

final class SnoozeDodgeParams {
  const SnoozeDodgeParams();
}

final class SnoozeDodgeState {
  const SnoozeDodgeState();
}

abstract final class SnoozeDodgeWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_snil9v3q",
      type: "Scaffold",
      path: "SnoozeDodge",
      name: "SnoozeDodge",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_034mxxah",
            type: "Container",
            path: "SnoozeDodge.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_zwmfy80t",
                type: "Column",
                path: "SnoozeDodge.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_71d3xs74",
                    type: "Container",
                    path: "SnoozeDodge.body[0].children[0].children[0]",
                    name: "DodgeStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_r47vva8s",
                        type: "Row",
                        path: "SnoozeDodge.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_oqzsom34",
                            type: "Text",
                            path: "SnoozeDodge.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_hhwbk1nn",
                            type: "Text",
                            path: "SnoozeDodge.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_f8gsa3wc",
                            type: "IconButton",
                            path: "SnoozeDodge.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_hwgwoae2",
                    type: "Column",
                    path: "SnoozeDodge.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Image_b7c0gedx",
                        type: "Image",
                        path: "SnoozeDodge.body[0].children[0].children[1].children[0]",
                        name: "AlbyBlocks",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ajaza7n6",
                        type: "Text",
                        path: "SnoozeDodge.body[0].children[0].children[1].children[1]",
                        name: "Text",
                        text: "Hold on!",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_lbo2yvft",
                        type: "Text",
                        path: "SnoozeDodge.body[0].children[0].children[1].children[2]",
                        name: "Text",
                        text: "You can't snooze just yet.\nLet's complete a quick verification first!",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_c0tnmahv",
                        type: "Text",
                        path: "SnoozeDodge.body[0].children[0].children[1].children[3]",
                        name: "Text",
                        text: "Almost! :)",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_9hbxhm1j",
                        type: "Text",
                        path: "SnoozeDodge.body[0].children[0].children[1].children[4]",
                        name: "Text",
                        text: "Fine. One more try.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_qqkmme1k",
                        type: "Container",
                        path: "SnoozeDodge.body[0].children[0].children[1].children[5]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_fjjs3h3b",
                            type: "Column",
                            path: "SnoozeDodge.body[0].children[0].children[1].children[5].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_dqedv995",
                                type: "Row",
                                path: "SnoozeDodge.body[0].children[0].children[1].children[5].children[0].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_7g56lwma",
                                    type: "Button",
                                    path: "SnoozeDodge.body[0].children[0].children[1].children[5].children[0].children[0].children[0]",
                                    name: "DodgeSnoozeCenter",
                                    text: "SNOOZE",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_lk74tmx5",
                                type: "Row",
                                path: "SnoozeDodge.body[0].children[0].children[1].children[5].children[0].children[1]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_q39kpqkw",
                                    type: "Button",
                                    path: "SnoozeDodge.body[0].children[0].children[1].children[5].children[0].children[1].children[0]",
                                    name: "DodgeSnoozeLeft",
                                    text: "SNOOZE",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_odd6lukg",
                                type: "Row",
                                path: "SnoozeDodge.body[0].children[0].children[1].children[5].children[0].children[2]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_qwa5la6v",
                                    type: "Button",
                                    path: "SnoozeDodge.body[0].children[0].children[1].children[5].children[0].children[2].children[0]",
                                    name: "DodgeSnoozeRight",
                                    text: "SNOOZE",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

