// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final snoozeApprovalHandle = ffai.ProjectPageHandle<SnoozeApprovalParams, SnoozeApprovalState>(
  name: "SnoozeApproval",
  key: "Scaffold_xs8dfx9e",
  route: "snooze-approval",
  params: const SnoozeApprovalParams(),
  state: const SnoozeApprovalState(),
  widgets: SnoozeApprovalWidgets.tree,
);

final class SnoozeApprovalParams {
  const SnoozeApprovalParams();
}

final class SnoozeApprovalState {
  const SnoozeApprovalState();
}

abstract final class SnoozeApprovalWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_xs8dfx9e",
      type: "Scaffold",
      path: "SnoozeApproval",
      name: "SnoozeApproval",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_emktvdis",
            type: "Container",
            path: "SnoozeApproval.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_dq6a18b0",
                type: "Column",
                path: "SnoozeApproval.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_pws9ja3x",
                    type: "Container",
                    path: "SnoozeApproval.body[0].children[0].children[0]",
                    name: "ApprovalStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_9xsrbqcr",
                        type: "Row",
                        path: "SnoozeApproval.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_d32f30ki",
                            type: "Text",
                            path: "SnoozeApproval.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_7g018xq1",
                            type: "Text",
                            path: "SnoozeApproval.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_3io5cdok",
                            type: "IconButton",
                            path: "SnoozeApproval.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_e44oggqj",
                    type: "Column",
                    path: "SnoozeApproval.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_ueo2ughn",
                        type: "Container",
                        path: "SnoozeApproval.body[0].children[0].children[1].children[0]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Image_gkgwqqo2",
                        type: "Image",
                        path: "SnoozeApproval.body[0].children[0].children[1].children[1]",
                        name: "AlbyCelebrates",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_svpnl81l",
                        type: "Text",
                        path: "SnoozeApproval.body[0].children[0].children[1].children[2]",
                        name: "Text",
                        text: "KYA Verified!",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_n3oycp2e",
                        type: "Text",
                        path: "SnoozeApproval.body[0].children[0].children[1].children[3]",
                        name: "Text",
                        text: "Identity confirmed. Alarm silenced.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_n33j3am9",
                        type: "Container",
                        path: "SnoozeApproval.body[0].children[0].children[1].children[4]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_hipcqb0y",
                            type: "Column",
                            path: "SnoozeApproval.body[0].children[0].children[1].children[4].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_vljjk1b8",
                                type: "Text",
                                path: "SnoozeApproval.body[0].children[0].children[1].children[4].children[0].children[0]",
                                name: "Text",
                                text: "AUTHORIZED SNOOZE PERIOD",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_122xq2zy",
                                type: "Text",
                                path: "SnoozeApproval.body[0].children[0].children[1].children[4].children[0].children[1]",
                                name: "Text",
                                text: "00:00:30",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_elmlz6zc",
                                type: "Text",
                                path: "SnoozeApproval.body[0].children[0].children[1].children[4].children[0].children[2]",
                                name: "Text",
                                text: "(You wish.)",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_2qrbfbo7",
                        type: "Container",
                        path: "SnoozeApproval.body[0].children[0].children[1].children[5]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_292omvkl",
                        type: "Button",
                        path: "SnoozeApproval.body[0].children[0].children[1].children[6]",
                        name: "StartSnoozeButton",
                        text: "YAY...",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_eeoqa2nw",
                        type: "Text",
                        path: "SnoozeApproval.body[0].children[0].children[1].children[7]",
                        name: "Text",
                        text: "Remember: productivity is a choice.\nSo is suffering.",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

