// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final wakefulnessCAPTCHAHandle = ffai.ProjectPageHandle<WakefulnessCAPTCHAParams, WakefulnessCAPTCHAState>(
  name: "WakefulnessCAPTCHA",
  key: "Scaffold_6fdgyrgq",
  route: "wakefulness-captcha",
  params: const WakefulnessCAPTCHAParams(),
  state: const WakefulnessCAPTCHAState(),
  widgets: WakefulnessCAPTCHAWidgets.tree,
);

final class WakefulnessCAPTCHAParams {
  const WakefulnessCAPTCHAParams();
}

final class WakefulnessCAPTCHAState {
  const WakefulnessCAPTCHAState();
}

abstract final class WakefulnessCAPTCHAWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_6fdgyrgq",
      type: "Scaffold",
      path: "WakefulnessCAPTCHA",
      name: "WakefulnessCAPTCHA",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_qpyj5ase",
            type: "Container",
            path: "WakefulnessCAPTCHA.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_7lnpcrnr",
                type: "Column",
                path: "WakefulnessCAPTCHA.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_x2tf4sli",
                    type: "Container",
                    path: "WakefulnessCAPTCHA.body[0].children[0].children[0]",
                    name: "CaptchaStatusBar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_gdrav4az",
                        type: "Row",
                        path: "WakefulnessCAPTCHA.body[0].children[0].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_9mzd3d0d",
                            type: "Text",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "6:00",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_ubpgbh5g",
                            type: "Text",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "CASE KYA-0018",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_w6du8hiu",
                            type: "IconButton",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[0].children[0].children[2]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_b7d8ynb2",
                    type: "Column",
                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_g3bntb2k",
                        type: "Container",
                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[0]",
                        name: "CaptchaStep",
                        componentName: "StepProgress",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_1lmy7cj6",
                        type: "Row",
                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_7hujnzoj",
                            type: "Column",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[1].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_s315c053",
                                type: "Text",
                                path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[1].children[0].children[0]",
                                name: "Text",
                                text: "Verify you're awake.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_jus3ac1u",
                                type: "Text",
                                path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[1].children[0].children[1]",
                                name: "Text",
                                text: "Select all objects you would rather be using right now.",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Image_wmngv060",
                            type: "Image",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[1].children[1]",
                            name: "AlbyInspects",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_au2iaaat",
                        type: "Row",
                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_dd3t5p10",
                            type: "Container",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[0]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Stack_xfyb2eyw",
                                type: "Stack",
                                path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[0].children[0]",
                                name: "Stack",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_ttm46sw0",
                                    type: "Column",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_zjlr5wmr",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[0].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_69o29uqt",
                                        type: "Text",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[0].children[0].children[0].children[1]",
                                        name: "Text",
                                        text: "Bed",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_l36agj68",
                                    type: "Row",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[0].children[0].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_ubvo88h7",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[0].children[0].children[1].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_cepewxxy",
                            type: "Container",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[1]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Stack_vqspthr5",
                                type: "Stack",
                                path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[1].children[0]",
                                name: "Stack",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_gb84dfp8",
                                    type: "Column",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[1].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_vc2dt7wk",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[1].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_1x8278ed",
                                        type: "Text",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[1].children[0].children[0].children[1]",
                                        name: "Text",
                                        text: "Coffee",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_9dazwstz",
                                    type: "Row",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[1].children[0].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_y4juzs8f",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[1].children[0].children[1].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_o69mnhp0",
                            type: "Container",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[2]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Stack_8xdn6zua",
                                type: "Stack",
                                path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[2].children[0]",
                                name: "Stack",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_pcnddukl",
                                    type: "Column",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[2].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_ndmveiwx",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[2].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_n4zjv03v",
                                        type: "Text",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[2].children[0].children[0].children[1]",
                                        name: "Text",
                                        text: "Laptop",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_zjctpws8",
                                    type: "Row",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[2].children[0].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_cmh5zmbh",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[2].children[2].children[0].children[1].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_730a563m",
                        type: "Row",
                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_cp6x88qy",
                            type: "Container",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[0]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Stack_vtvss3rs",
                                type: "Stack",
                                path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[0].children[0]",
                                name: "Stack",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_t86mpj6d",
                                    type: "Column",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_b84tt812",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[0].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_6eeb6m0z",
                                        type: "Text",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[0].children[0].children[0].children[1]",
                                        name: "Text",
                                        text: "Pillow",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_j0evme7j",
                                    type: "Row",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[0].children[0].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_kkcaz8eg",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[0].children[0].children[1].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_vvezczdz",
                            type: "Container",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[1]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Stack_efgqrnqd",
                                type: "Stack",
                                path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[1].children[0]",
                                name: "Stack",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_2w34hwg9",
                                    type: "Column",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[1].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_65ypsvmz",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[1].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_ydvmddpg",
                                        type: "Text",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[1].children[0].children[0].children[1]",
                                        name: "Text",
                                        text: "Dumbbell",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_5fivkkg8",
                                    type: "Row",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[1].children[0].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_rwnessfl",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[1].children[0].children[1].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_ida164qy",
                            type: "Container",
                            path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[2]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Stack_n35lu4dx",
                                type: "Stack",
                                path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[2].children[0]",
                                name: "Stack",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_bgm44124",
                                    type: "Column",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[2].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_y6dhfpgh",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[2].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_oc9lr089",
                                        type: "Text",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[2].children[0].children[0].children[1]",
                                        name: "Text",
                                        text: "Airplane",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_mq3twujz",
                                    type: "Row",
                                    path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[2].children[0].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_0sc0ryag",
                                        type: "Icon",
                                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[3].children[2].children[0].children[1].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_j4atzj52",
                        type: "Container",
                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[4]",
                        name: "CaptchaFailureBanner",
                        componentName: "AlertBanner",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_8bv3v2do",
                        type: "Button",
                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[5]",
                        name: "CaptchaVerifyButton",
                        text: "VERIFY SELECTION",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_nm2s1ord",
                        type: "Button",
                        path: "WakefulnessCAPTCHA.body[0].children[0].children[1].children[6]",
                        name: "CaptchaRetryButton",
                        text: "TRY AGAIN",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

