// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class AppState {
  static const alarmReturned = ffai.ProjectAppStateFieldHandle(
    name: "alarmReturned",
    key: "i744zyfn",
    typeName: "Boolean",
    persisted: false,
  );
  static const captchaAirplane = ffai.ProjectAppStateFieldHandle(
    name: "captchaAirplane",
    key: "euapp6ef",
    typeName: "Boolean",
    persisted: false,
  );
  static const captchaAttempt = ffai.ProjectAppStateFieldHandle(
    name: "captchaAttempt",
    key: "rwb347lr",
    typeName: "Integer",
    persisted: false,
  );
  static const captchaBed = ffai.ProjectAppStateFieldHandle(
    name: "captchaBed",
    key: "cl3sgd8f",
    typeName: "Boolean",
    persisted: false,
  );
  static const captchaCoffee = ffai.ProjectAppStateFieldHandle(
    name: "captchaCoffee",
    key: "d5s00gm0",
    typeName: "Boolean",
    persisted: false,
  );
  static const captchaDumbbell = ffai.ProjectAppStateFieldHandle(
    name: "captchaDumbbell",
    key: "l28t7617",
    typeName: "Boolean",
    persisted: false,
  );
  static const captchaFailed = ffai.ProjectAppStateFieldHandle(
    name: "captchaFailed",
    key: "5s0rtqtv",
    typeName: "Boolean",
    persisted: false,
  );
  static const captchaLaptop = ffai.ProjectAppStateFieldHandle(
    name: "captchaLaptop",
    key: "79wyuaow",
    typeName: "Boolean",
    persisted: false,
  );
  static const captchaPillow = ffai.ProjectAppStateFieldHandle(
    name: "captchaPillow",
    key: "fjx2rweg",
    typeName: "Boolean",
    persisted: false,
  );
  static const dodgeCount = ffai.ProjectAppStateFieldHandle(
    name: "dodgeCount",
    key: "mu49a0jc",
    typeName: "Integer",
    persisted: false,
  );
  static const identityComplete = ffai.ProjectAppStateFieldHandle(
    name: "identityComplete",
    key: "undpzufk",
    typeName: "Boolean",
    persisted: false,
  );
  static const identityScanning = ffai.ProjectAppStateFieldHandle(
    name: "identityScanning",
    key: "ehf7chjd",
    typeName: "Boolean",
    persisted: false,
  );
  static const identityTick = ffai.ProjectAppStateFieldHandle(
    name: "identityTick",
    key: "06of2gyi",
    typeName: "Integer",
    persisted: false,
  );
  static const officerRejected = ffai.ProjectAppStateFieldHandle(
    name: "officerRejected",
    key: "06ih27dr",
    typeName: "Boolean",
    persisted: false,
  );
  static const officerTestimony = ffai.ProjectAppStateFieldHandle(
    name: "officerTestimony",
    key: "2huc4uop",
    typeName: "String",
    persisted: false,
  );
  static const processingTick = ffai.ProjectAppStateFieldHandle(
    name: "processingTick",
    key: "hmth6m9i",
    typeName: "Integer",
    persisted: false,
  );
  static const reasonError = ffai.ProjectAppStateFieldHandle(
    name: "reasonError",
    key: "2l31y7aq",
    typeName: "String",
    persisted: false,
  );
  static const reasonText = ffai.ProjectAppStateFieldHandle(
    name: "reasonText",
    key: "s0i36425",
    typeName: "String",
    persisted: false,
  );
  static const secondsLeft = ffai.ProjectAppStateFieldHandle(
    name: "secondsLeft",
    key: "7hddgfv9",
    typeName: "Integer",
    persisted: false,
  );
  static const selectedReason = ffai.ProjectAppStateFieldHandle(
    name: "selectedReason",
    key: "szbtme70",
    typeName: "String",
    persisted: false,
  );
  static const snoozeCount = ffai.ProjectAppStateFieldHandle(
    name: "snoozeCount",
    key: "snoozeCount",
    typeName: "Integer",
    persisted: false,
  );
  static const all = <ffai.ProjectAppStateFieldHandle>[
    alarmReturned,
    captchaAirplane,
    captchaAttempt,
    captchaBed,
    captchaCoffee,
    captchaDumbbell,
    captchaFailed,
    captchaLaptop,
    captchaPillow,
    dodgeCount,
    identityComplete,
    identityScanning,
    identityTick,
    officerRejected,
    officerTestimony,
    processingTick,
    reasonError,
    reasonText,
    secondsLeft,
    selectedReason,
    snoozeCount,
  ];
}

