// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'components/alert_banner.dart' show AlertBannerComponentHandle;
import 'components/case_footer.dart' show CaseFooterComponentHandle;
import 'components/chat_bubble.dart' show ChatBubbleComponentHandle;
import 'components/official_seal.dart' show OfficialSealComponentHandle;
import 'components/step_progress.dart' show StepProgressComponentHandle;

abstract final class Components {
  static final alertBanner = AlertBannerComponentHandle();
  static final caseFooter = CaseFooterComponentHandle();
  static final chatBubble = ChatBubbleComponentHandle();
  static final officialSeal = OfficialSealComponentHandle();
  static final stepProgress = StepProgressComponentHandle();
  static final all = <ffai.ProjectComponentHandle>[
    alertBanner,
    caseFooter,
    chatBubble,
    officialSeal,
    stepProgress,
  ];
}
