// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'pages/aisnooze_officer.dart' show aisnoozeOfficerHandle;
import 'pages/active_alarm.dart' show activeAlarmHandle;
import 'pages/alarm_stopped.dart' show alarmStoppedHandle;
import 'pages/authorized_snooze.dart' show authorizedSnoozeHandle;
import 'pages/bureaucratic_processing.dart' show bureaucraticProcessingHandle;
import 'pages/identity_wake_check.dart' show identityWakeCheckHandle;
import 'pages/kyaintroduction.dart' show kyaintroductionHandle;
import 'pages/reason_for_snoozing.dart' show reasonForSnoozingHandle;
import 'pages/snooze_approval.dart' show snoozeApprovalHandle;
import 'pages/snooze_dodge.dart' show snoozeDodgeHandle;
import 'pages/wakefulness_captcha.dart' show wakefulnessCAPTCHAHandle;

abstract final class Pages {
  static final aisnoozeOfficer = aisnoozeOfficerHandle;
  static final activeAlarm = activeAlarmHandle;
  static final alarmStopped = alarmStoppedHandle;
  static final authorizedSnooze = authorizedSnoozeHandle;
  static final bureaucraticProcessing = bureaucraticProcessingHandle;
  static final identityWakeCheck = identityWakeCheckHandle;
  static final kyaintroduction = kyaintroductionHandle;
  static final reasonForSnoozing = reasonForSnoozingHandle;
  static final snoozeApproval = snoozeApprovalHandle;
  static final snoozeDodge = snoozeDodgeHandle;
  static final wakefulnessCAPTCHA = wakefulnessCAPTCHAHandle;
  static final all = <ffai.ProjectPageHandle>[
    aisnoozeOfficer,
    activeAlarm,
    alarmStopped,
    authorizedSnooze,
    bureaucraticProcessing,
    identityWakeCheck,
    kyaintroduction,
    reasonForSnoozing,
    snoozeApproval,
    snoozeDodge,
    wakefulnessCAPTCHA,
  ];
}
