// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class Project {
  static const id = "snooze-compliance-cxmajk";
  static const name = "Snooze Compliance";
  static const sdkMetaVersion = 3;
}
