// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
// ignore_for_file: unnecessary_this

library;

import 'dart:collection';

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Enums {
  static const all = <ffai.EnumHandle>[];
}

abstract final class Structs {
  static const all = <ffai.StructHandle>[];
}

abstract final class Collections {
  static const all = <ffai.ProjectCollectionHandle>[];
}

abstract final class Tables {
  static const all = <ffai.ProjectTableHandle>[];
}

abstract final class CustomCode {
  static const functions = <String>[
    "kyaAnyCaptchaSelected",
    "kyaCountdownLabel",
    "kyaDecrement",
    "kyaHasSufficientReason",
    "kyaIdentityComplete",
    "kyaIdentityPhase",
    "kyaIdentityPrompt",
    "kyaIdentityValue",
    "kyaIncrement",
    "kyaProcessingComplete",
    "kyaProcessingNote",
    "kyaProcessingPercent",
    "kyaProcessingValue",
    "kyaScanButtonLabel",
    "kyaTaskState",
  ];
  static const actions = <String>[
    "kyaStartAlarm",
    "kyaStopAlarm",
  ];
  static const widgets = <String>[
    "KyaFaceScan",
    "KyaProgressBar",
  ];
}

